# =============================================================================
# TERRAGRUNT SECURITY CONFIGURATION
# =============================================================================
# Enterprise security scanning configuration for TFSec
# Following SOC2, ISO 27001, and PCI-DSS compliance requirements

# General settings
include:
- '*'

exclude:
# Exclude third-party modules from scanning (they should be pre-validated)
- '**/.terragrunt-cache/**'
- '**/node_modules/**'
- '**/.terraform/**'

# Minimum severity level for reporting
minimum_severity: HIGH

# Custom rule configuration
custom_checks:
- check_id: YOV-SEC-001
  name: "Ensure all S3 buckets have versioning enabled"
  description: "S3 buckets must have versioning enabled for data protection"

- check_id: YOV-SEC-002
  name: "Ensure RDS instances use encrypted storage"
  description: "All RDS instances must use encrypted storage for data protection"

- check_id: YOV-SEC-003
  name: "Ensure EKS clusters have logging enabled"
  description: "EKS clusters must have audit logging enabled for security monitoring"

# Rule customization
rule_overrides:
  # AWS specific rules
  aws-s3-bucket-public-access-block:
    severity: CRITICAL

  aws-rds-encrypt-instance-storage-data:
    severity: CRITICAL

  aws-eks-enable-control-plane-logging:
    severity: HIGH

  aws-vpc-no-default-vpc:
    severity: MEDIUM

  aws-iam-no-policy-wildcards:
    severity: HIGH

  aws-kms-auto-rotate-keys:
    severity: HIGH

# Compliance framework mapping
compliance_frameworks:
  SOC2:
  - aws-s3-encryption-customer-key
  - aws-rds-encrypt-instance-storage-data
  - aws-cloudtrail-encryption-enabled
  - aws-eks-enable-control-plane-logging

  ISO27001:
  - aws-iam-no-policy-wildcards
  - aws-s3-bucket-public-access-block
  - aws-vpc-enable-flow-logs
  - aws-kms-auto-rotate-keys

  PCI-DSS:
  - aws-rds-encrypt-instance-storage-data
  - aws-s3-encryption-customer-key
  - aws-cloudtrail-encryption-enabled
  - aws-vpc-no-public-ingress-sgr

# Exclude specific checks that may not apply to our architecture
exclude_rules:
# These may be acceptable in certain controlled environments
- aws-s3-bucket-public-read-prohibited # We may have controlled public assets
- aws-ec2-no-public-ip # NAT instances may need public IPs
