# =============================================================================
# OPEN POLICY AGENT CONFIGURATION
# =============================================================================
# Configuration for OPA policy evaluation in CI/CD pipeline

services:
  authz:
    url: https://opa.yov.com

bundles:
  terraform:
    service: authz
    resource: "terraform/policies"
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

decision_logs:
  console: true
  reporting:
    min_delay_seconds: 5
    max_delay_seconds: 15

status:
  console: true

server:
  addr: localhost:8181
  diagnostic-addr: localhost:8282

storage:
  disk:
    directory: "/tmp/opa"
